select max(fetchstamp) from BU;
select max(fetchstamp) from EVM                            ;
select max(fetchstamp) from EventProcessorLegend;     
select max(fetchstamp) from EventProcessorScalersLegend;
select max(fetchstamp) from EventProcessorStatus           ;
select max(fetchstamp) from FMMFEDDeadTime                 ;
select max(fetchstamp) from FMMInput                       ;
select max(fetchstamp) from FMMInputDetail                 ;
select max(fetchstamp) from FMMPartitionDeadTime           ;
select max(fetchstamp) from FMMStatus                      ;
select max(fetchstamp) from HLTS_L1Scalers                 ;
select max(fetchstamp) from RU                             ;
select max(fetchstamp) from ResourceBroker                 ;
select max(fetchstamp) from StorageManagerPerformance      ;
select max(fetchstamp) from diskInfo                       ;
select max(fetchstamp) from fbo                            ;
select max(fetchstamp) from fetchstamps;
select max(fetchstamp) from frlBxHisto;
select max(fetchstamp) from frlWcHisto;
select max(fetchstamp) from frlcontrollerCard;
select max(fetchstamp) from frlcontrollerLink;
select max(fetchstamp) from frlcontrollerStatus;
select max(fetchstamp) from frllinkdbmondata;
select max(fetchstamp) from gmt_cell_mon;
select max(fetchstamp) from gmt_cell_scalers_act;
select max(fetchstamp) from gmt_cell_scalers_pas;
select max(fetchstamp) from gmt_cell_status;
select max(fetchstamp) from gt_cell_general;
select max(fetchstamp) from gt_cell_lumiseg;
select max(fetchstamp) from gt_cell_trigger_table;
select max(fetchstamp) from gt_cell_ttcpartitions;
select max(fetchstamp) from hltCpuUsage;
select max(fetchstamp) from hostInfo;
select max(fetchstamp) from jobcontrol;
select max(fetchstamp) from l1ts_cell;
select max(fetchstamp) from l1ts_dbjobs;
select max(fetchstamp) from levelZeroFM_dynamic;
select max(fetchstamp) from levelZeroFM_static;
select max(fetchstamp) from levelZeroFM_subsys;
